"""add phone user column 

Revision ID: 6d172e2c3fdc
Revises: 2c306c0a78d3
Create Date: 2022-03-13 19:20:27.497222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d172e2c3fdc'
down_revision = '2c306c0a78d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
